/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StatementList = {
  id: string;
  text: string;
  /**
   * Non-empty by design — a statement with no cited transcript span cannot exist. This is the schema-level enforcement of 'no hallucinated claims.'
   *
   * @minItems 1
   */
  evidence: [string, ...string[]];
  confidence?: number;
  [k: string]: unknown;
}[];

export interface SoapNote {
  encounter_id: string;
  model: {
    name: "llama-3-8b-instruct";
    quant: string;
    prompt_version: string;
    [k: string]: unknown;
  };
  generated_at: string;
  sections: {
    subjective: StatementList;
    objective: StatementList;
    assessment: StatementList;
    plan: StatementList;
    [k: string]: unknown;
  };
  medications?: {
    id: string;
    verbatim: string;
    /**
     * FK into the local ingredient_dictionary table. Null if unresolved.
     */
    ingredient_id?: string | null;
    match_confidence?: number;
    needs_manual_confirmation?: boolean;
    dose?: {
      value?: number;
      unit?: string;
      [k: string]: unknown;
    };
    frequency?: string;
    route?: string;
    duration_days?: number;
    /**
     * @minItems 1
     */
    evidence: [string, ...string[]];
    flags: SafetyFlag[];
    [k: string]: unknown;
  }[];
  differential_considerations?: {
    label: string;
    /**
     * @minItems 1
     */
    trigger_spans: [string, ...string[]];
    rationale: string;
    [k: string]: unknown;
  }[];
  safety_flags?: SafetyFlag[];
  grounding: {
    statements_total: number;
    ungrounded: number;
    ungrounded_ids: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface SafetyFlag {
  severity: "low" | "moderate" | "high";
  type: "interaction" | "dose_range" | "unresolved_medication";
  pair?: string[];
  /**
   * Mandatory citation, e.g. 'ONC-HighPriority#412' or 'DDInter2#88014'. Never null — an interaction flag with no source is not permitted.
   */
  source_ref: string;
  message: string;
  [k: string]: unknown;
}
